apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: space-traders

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yml

  - deployment.yml
  - service.yml
  - ingress.yml

  # - redis/deployment.yml
  # - redis/service.yml

  # - product_page/ingress.yml
  # - product_page/service.yml
  # - product_page/deployment.yml
